site_name: ratp_poll documentation
site_url: https://cgupm.github.io/ratp_poll
repo_name: 'cgupm/ratp_poll'
repo_url: 'https://github.com/cgupm/ratp_poll'

nav:
  - Overview: index.md
  - Reference:
      - cli.py: reference/cli.md
      - ratp_api:
        - stop_times.py: reference/ratp_api/stop_times.md
      - daemon:
        - daemon.py: reference/daemon/daemon.md

plugins:
  - search
  - autolinks
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - ../ratp_poll
  - git-revision-date-localized:
      type: timeago

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
